# Generated by Django 5.0.2 on 2024-08-16 06:20

from django.db import migrations

def create_initial_data(apps, schema_editor):
    Domain = apps.get_model('core', 'Domain')
    AlertTypeMaster = apps.get_model('core', 'AlertTypeMaster')
    SubscriptionPlan = apps.get_model('core', 'SubscriptionPlan')


#adding initial DOmains
    general_surveillance = Domain.objects.create(name='General Surveillance')
    office = Domain.objects.create(name='Office')
    
   

# adding initial AlertTypes
    AlertTypeMaster.objects.create(domain=general_surveillance, type='TOP', name='Talking On Phone')
    AlertTypeMaster.objects.create(domain=general_surveillance, type='PWB', name='Person With Bottle')
    AlertTypeMaster.objects.create(domain=general_surveillance, type='Fire', name='Fire and Smoke')
    AlertTypeMaster.objects.create(domain=office, type='UD', name='Unocupied Desk')
    AlertTypeMaster.objects.create(domain=office, type='TOP', name='Talking on Phone')
    AlertTypeMaster.objects.create(domain=office, type='Fire', name='Fire and Smoke')
    