name: Build, Push, and Deploy to ECS

on:
  push:
    branches:
      - main  # Trigger only on main branch commits

env:
  AWS_REGION: ap-south-1
  CLUSTER_NAME: Dem-Cluster
  SERVICE_NAME: ecs-task-service-bn4bpjfz
  IMAGE_NAME: ayushv274/ecs-demo:v1

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Set image tag based on commit SHA
      - name: Set image tag
        id: vars
        run: echo "TAG=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV

      # 3. Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 4. Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.TAG }}
            ${{ env.IMAGE_NAME }}:latest

      # 5. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # 6. Get current task definition JSON
      - name: Get current ECS task definition
        id: taskdef
        run: |
          TASK_DEF=$(aws ecs describe-task-definition \
            --task-definition ecs-task \
            --query taskDefinition)
          echo "$TASK_DEF" > taskdef.json

      # 7. Update task definition with new image tag
      - name: Update task definition with new image
        run: |
          NEW_TASK_DEF=$(jq --arg IMAGE "${{ env.IMAGE_NAME }}:${{ env.TAG }}" \
            '.containerDefinitions[0].image = $IMAGE' taskdef.json)
          echo "$NEW_TASK_DEF" > new-taskdef.json

      # 8. Register new task definition revision
      - name: Register new task definition
        run: |
          aws ecs register-task-definition \
            --cli-input-json file://new-taskdef.json

      # 9. Update ECS service to use new task definition
      - name: Deploy new task definition
        run: |
          aws ecs update-service \
            --cluster ${{ env.CLUSTER_NAME }} \
            --service ${{ env.SERVICE_NAME }} \
            --force-new-deployment
