name: Deployment of Piloo-BE

on:
  push:
    branches: [ "staging" ]
  workflow_dispatch:

jobs:
  Delete:
    name: Deleting folder
    runs-on: beast
    # needs: Build
    steps:
      - run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo -S rm -rf /home/piloo/piloo-BE/piloobe
      
  Checkout:
    runs-on: beast
    needs: Delete
    steps:
      - uses: actions/checkout@v4 

  # CleanUp:
  #   name: Deleting cache files
  #   runs-on: beast
  #   needs: Checkout

  #   steps:
  #     - name: Clean
  #       run: sudo docker system prune -f --all

  Deploy:
    name: Build and Deploy
    runs-on: beast
    needs: Checkout

    steps: 
      - run: echo "${{ secrets.SUDO_PASSWORD }}" | sudo docker compose -f docker-compose.stage.yml up -d --build --force-recreate
